/*

 MARSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 14 x 36
   Tile set      : C:\Users\leo-c\OneDrive\Área de Trabalho\CCPP\gameboydev\GBTD\shooter_mars.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __MarsMap_h_INCLUDE
#define __MarsMap_h_INCLUDE

#define MarsMapWidth 14
#define MarsMapHeight 36
#define MarsMapBank 1

#define MarsMap MarsMapPLN0
extern const void __bank_MarsMapPLN0;
extern const unsigned char MarsMapPLN0[];
extern const void __bank_MarsMapPLN01;
extern const unsigned char MarsMapPLN1[];

#endif

/* End of MARSMAP.H */
