/*

 MARSTILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 2 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __MarsTileset_h_INCLUDE
#define __MarsTileset_h_INCLUDE

/* Bank of tiles. */
#define MarsTilesetBank 1

/* Gameboy Color palette 0 */
#define MarsTilesetCGBPal0c0 6076
#define MarsTilesetCGBPal0c1 8935
#define MarsTilesetCGBPal0c2 6596
#define MarsTilesetCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define MarsTilesetCGBPal1c0 16926
#define MarsTilesetCGBPal1c1 8479
#define MarsTilesetCGBPal1c2 22
#define MarsTilesetCGBPal1c3 17

/* Gameboy Color palette 2 */
#define MarsTilesetCGBPal2c0 16926
#define MarsTilesetCGBPal2c1 21074
#define MarsTilesetCGBPal2c2 13642
#define MarsTilesetCGBPal2c3 8357

/* Gameboy Color palette 3 */
#define MarsTilesetCGBPal3c0 6076
#define MarsTilesetCGBPal3c1 8935
#define MarsTilesetCGBPal3c2 6596
#define MarsTilesetCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define MarsTilesetCGBPal4c0 6076
#define MarsTilesetCGBPal4c1 8935
#define MarsTilesetCGBPal4c2 6596
#define MarsTilesetCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define MarsTilesetCGBPal5c0 6076
#define MarsTilesetCGBPal5c1 8935
#define MarsTilesetCGBPal5c2 6596
#define MarsTilesetCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define MarsTilesetCGBPal6c0 6076
#define MarsTilesetCGBPal6c1 8935
#define MarsTilesetCGBPal6c2 6596
#define MarsTilesetCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define MarsTilesetCGBPal7c0 6076
#define MarsTilesetCGBPal7c1 8935
#define MarsTilesetCGBPal7c2 6596
#define MarsTilesetCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char MarsTilesetCGB[];
/* Start of tile array. */
extern const unsigned char MarsTileset[];

const UWORD MARS_PALETTE[] = {
    MarsTilesetCGBPal1c0,
    MarsTilesetCGBPal1c1,
    MarsTilesetCGBPal1c2,
    MarsTilesetCGBPal1c3,

    MarsTilesetCGBPal2c0,
    MarsTilesetCGBPal2c1,
    MarsTilesetCGBPal2c2,
    MarsTilesetCGBPal2c3,

    MarsTilesetCGBPal3c0,
    MarsTilesetCGBPal3c1,
    MarsTilesetCGBPal3c2,
    MarsTilesetCGBPal3c3,

    MarsTilesetCGBPal4c0,
    MarsTilesetCGBPal4c1,
    MarsTilesetCGBPal4c2,
    MarsTilesetCGBPal4c3,

    MarsTilesetCGBPal5c0,
    MarsTilesetCGBPal5c1,
    MarsTilesetCGBPal5c2,
    MarsTilesetCGBPal5c3,

    MarsTilesetCGBPal6c0,
    MarsTilesetCGBPal6c1,
    MarsTilesetCGBPal6c2,
    MarsTilesetCGBPal6c3,

    MarsTilesetCGBPal7c0,
    MarsTilesetCGBPal7c1,
    MarsTilesetCGBPal7c2,
    MarsTilesetCGBPal7c3
};

#endif

/* End of MARSTILESET.H */
