/*

 SHIPSPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ShipSprites_h_INCLUDE
#define __ShipSprites_h_INCLUDE

/* Bank of tiles. */
#define ShipSpritesBank 0

/* Super Gameboy palette 0 */
#define ShipSpritesSGBPal0c0 6076
#define ShipSpritesSGBPal0c1 8935
#define ShipSpritesSGBPal0c2 6596
#define ShipSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ShipSpritesSGBPal1c0 6076
#define ShipSpritesSGBPal1c1 8935
#define ShipSpritesSGBPal1c2 6596
#define ShipSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ShipSpritesSGBPal2c0 6076
#define ShipSpritesSGBPal2c1 8935
#define ShipSpritesSGBPal2c2 6596
#define ShipSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ShipSpritesSGBPal3c0 6076
#define ShipSpritesSGBPal3c1 8935
#define ShipSpritesSGBPal3c2 6596
#define ShipSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ShipSpritesCGBPal0c0 992
#define ShipSpritesCGBPal0c1 26260
#define ShipSpritesCGBPal0c2 15690
#define ShipSpritesCGBPal0c3 5186

/* Gameboy Color palette 1 */
#define ShipSpritesCGBPal1c0 992
#define ShipSpritesCGBPal1c1 11263
#define ShipSpritesCGBPal1c2 10591
#define ShipSpritesCGBPal1c3 5300

/* Gameboy Color palette 2 */
#define ShipSpritesCGBPal2c0 992
#define ShipSpritesCGBPal2c1 30270
#define ShipSpritesCGBPal2c2 32030
#define ShipSpritesCGBPal2c3 26648

/* Gameboy Color palette 3 */
#define ShipSpritesCGBPal3c0 992
#define ShipSpritesCGBPal3c1 32767
#define ShipSpritesCGBPal3c2 5407
#define ShipSpritesCGBPal3c3 1131

/* Gameboy Color palette 4 */
#define ShipSpritesCGBPal4c0 992
#define ShipSpritesCGBPal4c1 25930
#define ShipSpritesCGBPal4c2 32668
#define ShipSpritesCGBPal4c3 15525

/* Gameboy Color palette 5 */
#define ShipSpritesCGBPal5c0 992
#define ShipSpritesCGBPal5c1 32668
#define ShipSpritesCGBPal5c2 21140
#define ShipSpritesCGBPal5c3 10570

/* Gameboy Color palette 6 */
#define ShipSpritesCGBPal6c0 6076
#define ShipSpritesCGBPal6c1 8935
#define ShipSpritesCGBPal6c2 6596
#define ShipSpritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define ShipSpritesCGBPal7c0 6076
#define ShipSpritesCGBPal7c1 8935
#define ShipSpritesCGBPal7c2 6596
#define ShipSpritesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char ShipSpritesCGB[];
/* Start of tile array. */
extern const unsigned char ShipSprites[];

#endif

/* End of SHIPSPRITES.H */
