/*

 SPACETILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __SpaceTileset_h_INCLUDE
#define __SpaceTileset_h_INCLUDE

/* Bank of tiles. */
#define SpaceTilesetBank 1

/* Gameboy Color palette 0 */
#define SpaceTilesetCGBPal0c0 6076
#define SpaceTilesetCGBPal0c1 8935
#define SpaceTilesetCGBPal0c2 6596
#define SpaceTilesetCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define SpaceTilesetCGBPal1c0 7205
#define SpaceTilesetCGBPal1c1 32177
#define SpaceTilesetCGBPal1c2 16424
#define SpaceTilesetCGBPal1c3 31612

/* Gameboy Color palette 2 */
#define SpaceTilesetCGBPal2c0 7205
#define SpaceTilesetCGBPal2c1 24541
#define SpaceTilesetCGBPal2c2 767
#define SpaceTilesetCGBPal2c3 31612

/* Gameboy Color palette 3 */
#define SpaceTilesetCGBPal3c0 7205
#define SpaceTilesetCGBPal3c1 32126
#define SpaceTilesetCGBPal3c2 19791
#define SpaceTilesetCGBPal3c3 31612

/* Gameboy Color palette 4 */
#define SpaceTilesetCGBPal4c0 6076
#define SpaceTilesetCGBPal4c1 8935
#define SpaceTilesetCGBPal4c2 6596
#define SpaceTilesetCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SpaceTilesetCGBPal5c0 6076
#define SpaceTilesetCGBPal5c1 8935
#define SpaceTilesetCGBPal5c2 6596
#define SpaceTilesetCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define SpaceTilesetCGBPal6c0 6076
#define SpaceTilesetCGBPal6c1 8935
#define SpaceTilesetCGBPal6c2 6596
#define SpaceTilesetCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define SpaceTilesetCGBPal7c0 6076
#define SpaceTilesetCGBPal7c1 8935
#define SpaceTilesetCGBPal7c2 6596
#define SpaceTilesetCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char SpaceTilesetCGB[];
/* Start of tile array. */
extern const unsigned char SpaceTileset[];


const UWORD SPACE_PALETTE[] = {
    SpaceTilesetCGBPal1c0,
    SpaceTilesetCGBPal1c1,
    SpaceTilesetCGBPal1c2,
    SpaceTilesetCGBPal1c3,

    SpaceTilesetCGBPal2c0,
    SpaceTilesetCGBPal2c1,
    SpaceTilesetCGBPal2c2,
    SpaceTilesetCGBPal2c3,

    SpaceTilesetCGBPal3c0,
    SpaceTilesetCGBPal3c1,
    SpaceTilesetCGBPal3c2,
    SpaceTilesetCGBPal3c3,

    SpaceTilesetCGBPal4c0,
    SpaceTilesetCGBPal4c1,
    SpaceTilesetCGBPal4c2,
    SpaceTilesetCGBPal4c3,

    SpaceTilesetCGBPal5c0,
    SpaceTilesetCGBPal5c1,
    SpaceTilesetCGBPal5c2,
    SpaceTilesetCGBPal5c3,

    SpaceTilesetCGBPal6c0,
    SpaceTilesetCGBPal6c1,
    SpaceTilesetCGBPal6c2,
    SpaceTilesetCGBPal6c3,

    SpaceTilesetCGBPal7c0,
    SpaceTilesetCGBPal7c1,
    SpaceTilesetCGBPal7c2,
    SpaceTilesetCGBPal7c3
};

#endif

/* End of SPACETILESET.H */
